#!/usr/bin/env bash
set -euox pipefail

TAR="$(dirname "$0")"/$1.tgz
CPIO="$(dirname "$0")"/$1-initrd.gz

# Extract container image to directory (through temporary non-running container)
ID=$(podman create $1)
podman export $ID | gzip > $TAR
podman rm $ID

fakeroot ./image2initrd-fakeroot $TAR  $CPIO

echo "Initial RAM Disk CPIO archive written to $CPIO"
