#!/usr/bin/env bash
set -euox pipefail

WORK=/tmp/image2initrd/$$
mkdir -p $WORK

tar xvf $1 --directory=$WORK

# Clean up some files added by `podman create` (apparently)
rm $WORK/etc/hosts || true
rm $WORK/etc/resolv.conf || true
rm $WORK/run/.containerenv || true
rm -rf $WORK/run/secrets/ || true

# Now add stuff which is not in the container images
# (and can't be added via Dockerfile, because /dev/ is a tmpfs)
# as per `man null` (and required for tty* below)
mknod -m 666 $WORK/dev/null c 1 3
mknod -m 666 $WORK/dev/zero c 1 5
chown root:root /dev/null /dev/zero

# fix "can't open /dev/tty4: No such file or directory"
ln -sf /dev/null $WORK/dev/tty2
ln -sf /dev/null $WORK/dev/tty3
ln -sf /dev/null $WORK/dev/tty4

# Create Initial RAM Disk CPIO archive
( cd $WORK/ && find . | cpio -o -H newc ) | gzip > $2
rm -rf $1 $WORK
