#!/usr/bin/env bash
set -euox pipefail
cd "$(dirname "$0")"

# Build container (this includes actually building the Kernel in that container image)
./build

# Copy Kernel out of container image (by briefly running the container; TODO how to copy out of an image without run?)
podman run --detach --name kernel-dev-cp kernel-dev
podman cp kernel-dev-cp:/home/tux/linux-stable/linux /tmp/
podman rm --force kernel-dev-cp

# Actually run the UML container
/tmp/linux
