#!/usr/bin/env bash
set -euox pipefail

# TODO @Deprecated Replace caller with the newer ./run script, and delete this.

qemu-system-x86_64 \
    -nodefaults -no-user-config \
    -enable-kvm  -cpu host  -m 2048  -smp 2 \
    -net user  -nic user,ipv6=off \
    -serial stdio  -nographic  -display none \
    -kernel /tmp/bzImage  -append " console=ttyS0 rdinit=/init root=/dev/ram" \
    -initrd $1

# NB: Must use rdinit= instead of init= for -initrd! ;)
