#!/usr/bin/env bash
set -euo pipefail

# Args Input (removes trailing slash)
DIR="${1%/}"

# Internal (must match build-image & image2initrd)
IMAGE="$DIR.img"



qemu-system-x86_64 \
    -nodefaults -no-user-config \
    -enable-kvm  -cpu host  -m 512  -smp 2 \
    -nic user,net=10.0.99.0/24,model=virtio,hostfwd=tcp::2222-:22,hostfwd=tcp::5900-:5900,ipv6=off \
    -display gtk,zoom-to-fit=on \
    -drive file="$IMAGE",format=raw,index=0 &



# Memory 5120 MB = 2048 (for us) + 3072 (for run_archiso)
# SMP 8 instead of 2 makes mkarchiso much faster; it takes only 2m2s instead of 5m39s for baseline ISO,
# due to the parallel mksquashfs.  Not using xz but default gzip in mkinitcpio.conf saves another 30s,
# so baseline ISO now builds in ca. 100s.
