#!/usr/bin/env bash
set -euox pipefail
cd "$(dirname "$0")"

# Skipping Kernel re-build (so this is different from run-qemu, which still does that)
# $1 is that path of a Kernel bzImage
# $2 of the userland container image

# Prepare InitRD (from container image named "hello" which was created in `./build`)
./image2initrd $2
CPIO="$(dirname "$0")"/$2-initrd.gz

# Create boot disk image
# inspired by https://wiki.syslinux.org/wiki/index.php?title=Development/Testing
IMG=$1-$2.img
rm -f $IMG
qemu-img create -f raw $IMG 20M
mkfs.ext4 -v -L LinuxRootFS $IMG
udisksctl loop-setup --no-user-interaction -f $IMG
sudo extlinux --install /run/media/$USER/LinuxRootFS
sudo cp syslinux/* /run/media/$USER/LinuxRootFS
sudo mkdir /run/media/$USER/LinuxRootFS/boot/
sudo cp $1 /run/media/$USER/LinuxRootFS/boot/bzImage
sudo cp $CPIO /run/media/$USER/LinuxRootFS/boot/initrd.gz
sudo ls -alR /run/media/$USER/LinuxRootFS/
umount /run/media/$USER/LinuxRootFS/

# Actually run Kernel + InitRD
qemu-system-x86_64 \
    -no-user-config \
    -enable-kvm  -cpu host  -m 512  -smp 2 \
    -nic user,ipv6=off \
    -drive file=$IMG,format=raw
