#!/usr/bin/env bash
set -euox pipefail
cd "$(dirname "$0")"

# Build containers (this includes actually building the Kernel in that container image)
podman build -t kernel-qemu     -f containers/kernel-qemu.Dockerfile     /tmp

# Copy Kernel out of container image (by briefly running the container; TODO how to copy out of an image without run?)
podman run --detach --name kernel-qemu-cp kernel-qemu
podman cp kernel-qemu-cp:/home/tux/linux-stable/arch/x86/boot/bzImage /tmp/
podman rm --force kernel-qemu-cp

# Prepare InitRD (from container image named "hello" which was created in `./build`)
./image2initrd $1

# Actually run Kernel + InitRD
qemu-system-x86_64 \
    -enable-kvm  -cpu host  -m 512  -smp 2 \
    -serial stdio  -display none  -nic none \
    -kernel /tmp/bzImage  -append "console=ttyS0"  -initrd $1-initrd.gz
