#!/usr/bin/bash
set -euox pipefail

# https://gitlab.archlinux.org/archlinux/arch-boxes
if [ ! -f Arch-Linux-x86_64-basic.qcow2 ]; then
  curl -fSL# https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-basic.qcow2 \
          -o Arch-Linux-x86_64-basic.qcow2
fi

rm -f Arch-Linux-x86_64-basic_OVERLAY.qcow2 && \
  qemu-img create -o backing_file=Arch-Linux-x86_64-basic.qcow2,backing_fmt=qcow2 \
  -f qcow2 Arch-Linux-x86_64-basic_OVERLAY.qcow2

mkdir -p "$(dirname $1)"
rm -f $1 && truncate -s 10G $1

qemu-system-x86_64 \
     -no-user-config \
     -display gtk,zoom-to-fit=on \
     -enable-kvm  -cpu host  -m 2047  -smp 2 \
     -nic user,model=virtio,hostfwd=tcp::2222-:22,ipv6=off \
     -drive file=$1,format=raw,index=0 \
     -drive file=Arch-Linux-x86_64-basic_OVERLAY.qcow2,index=1,if=none,id=disk2 \
     -device virtio-blk-pci,drive=disk2,bootindex=1 &
#    -cdrom ~/Downloads/archlinux-2020.12.01-x86_64.iso
# https://www.qemu.org/docs/master/system/bootindex.html

# NB: It's pointless to await port 2222 (e.g. à la https://stackoverflow.com/a/70985361/421602),
# because QEMU is immediately forwarding it already anyway - even if the VM isn't actually listening, yet.
# 60s because of https://gitlab.archlinux.org/archlinux/arch-boxes/-/issues/153
# see https://github.com/vorburger/vorburger.ch-Notes/blob/develop/linux/systemd-analyze.md
sleep 60

sshpass -p arch scp -P 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=60 arch-install* arch@localhost:
sshpass -p arch ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null arch@localhost sudo bash ./arch-install-sda-mnt

sshpass -p arch ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null arch@localhost sudo umount -R /mnt

sshpass -p arch ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null arch@localhost sudo shutdown now || true
sleep 3

./start $1
