#!/usr/bin/bash
# https://wiki.archlinux.org/index.php/Installation_guide
set -euox pipefail

ln -sf /usr/share/zoneinfo/Europe/Zurich /etc/localtime
hwclock --systohc

systemctl enable sshd

syslinux-install_update -i -a -m
