// load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

// TODO Can this be in BUILD or does it have to be in WORKSPACE?
new_git_repository(
    name="arch-install-scripts",
    remote="git@github.com:archlinux/arch-install-scripts.git",
    commit="2aa70691e58a99e2bcef64eeaeaf82e2956909cd",
    verbose="true")

// TODO https://bazel.build/reference/be/shell to *build* pacstrap

// TODO genrule to *use* pacstrap
