#!/usr/bin/bash
set -euox pipefail

qemu-system-x86_64 \
     -no-user-config \
     -display gtk,zoom-to-fit=on \
     -enable-kvm  -cpu host  -m 2047  -smp 2 \
     -nic user,model=virtio,hostfwd=tcp::2222-:22,ipv6=off \
     -drive file=$1,format=raw
