#!/usr/bin/bash
set -euox pipefail

if [[ $# -ne 1 ]]; then
  echo "USAGE: $0 /dev/sda"
  exit 1
fi

drive="$1"
part1="$1"1

umount "${part1}" || true

parted --script "${drive}" \
    mklabel msdos \
    mkpart primary ext4 0G 100%

mkfs.ext4 -F "${part1}"

mount "${part1}" /mnt

rsync -aHAPv --delete --delete-excluded \
  --exclude=/mnt --exclude=/proc --exclude=/dev --exclude=/sys --exclude=/run --exclude=/tmp \
  --exclude=/var/log --exclude=/var/tmp \
  / /mnt

cat <<EOT >>/mnt/etc/fstab
${part1}              /               ext4            rw,relatime     0 1
EOT

mkdir -p /mnt/boot/syslinux/
cp /opt/dinstall/syslinux.cfg /mnt/boot/syslinux/
cp /run/archiso/bootmnt/arch/boot/x86_64/* /mnt/boot/
syslinux-install_update -i -a -m -c /mnt
